# The cluster to run in and the specific nodepools that
# should run kubeip and get a public ip assigned
cluster:
  name: primary-cluster
  kubeip_nodepool: kubeip-node
  public_nodepool: primary-node

# kubeip requires cluster admin rights so an end user is needed
# to authorize the resource
userEmail: user@gmail.com

image:
  repository: doitintl/kubeip
  pullPolicy: IfNotPresent

env_config:
  KUBEIP_LABELKEY: "kubeip"
  KUBEIP_LABELVALUE: "primary-cluster"
  KUBEIP_NODEPOOL: "primary-node"
  KUBEIP_FORCEASSIGNMENT: "true"
  KUBEIP_ADDITIONALNODEPOOLS: ""
  KUBEIP_TICKER: "5"
  KUBEIP_ALLNODEPOOLS: "false"
  KUBEIP_ORDERBYLABELKEY: "priority"
  KUBEIP_ORDERBYDESC: "true"
  KUBEIP_COPYLABELS: "false"
  KUBEIP_CLEARLABELS: "false"
  KUBEIP_DRYRUN: "false"
