apiVersion: v1
kind: Service
metadata:
  name: vdl-redis

spec:
  ports:
  - name: redis-port
    protocol: "TCP"
    port: 6379
    targetPort: 6379
  selector:
    app: vdl-redis

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: vdl-redis
  labels:
    app: vdl-redis

spec:
  replicas: 1
  selector:
    matchLabels:
      app: vdl-redis
  template:
    metadata:
      labels:
        app: vdl-redis
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: primary-node
      containers:
      - name: redis
        image: redis:7
        command:
          - redis-server
          - "/redis/redis.conf"
        ports:
          - containerPort: 6379
        resources:
          limits:
            cpu: "0.1"
        volumeMounts:
          - mountPath: /redis
            name: config
      volumes:
        - name: config
          configMap:
            name: redis-config
            items:
            - key: redis-config
              path: redis.conf

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis-config: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru    

